<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>A2.Server.Workers</RootNamespace>
    <AssemblyName>A2.Server.Workers</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1573</NoWarn>
    <OutputType>Exe</OutputType>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../A2.Server.Engine/A2.Server.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="7.0.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.2" />
    <PackageReference Include="AWSSDK.SSO" Version="4.0.0.7" />
    <PackageReference Include="AWSSDK.SSOOIDC" Version="4.0.0.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
  </ItemGroup>
</Project>
